import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../styles/globals.css";

// !Global fonts
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400"],
});

// !Metadata for the app
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// !App layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
